//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanShare.App.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTexts() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanShare.App.Resources.ResourceTexts", typeof(ResourceTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change password.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete my account.
        /// </summary>
        public static string DELETE_ACCOUNT {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The following erros were found.
        /// </summary>
        public static string FOLLOWING_ERROS_WERE_FOUND {
            get {
                return ResourceManager.GetString("FOLLOWING_ERROS_WERE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login With Email and Password.
        /// </summary>
        public static string LOGIN_WITH_EMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_WITH_EMAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Already have an account.
        /// </summary>
        public static string PHRASE_ALREADY_HAS_ACCOUNT {
            get {
                return ResourceManager.GetString("PHRASE_ALREADY_HAS_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Continue with Google.
        /// </summary>
        public static string PHRASE_CONTINUE_WITH_GOOGLE {
            get {
                return ResourceManager.GetString("PHRASE_CONTINUE_WITH_GOOGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log in!.
        /// </summary>
        public static string PHRASE_DO_LOGIN {
            get {
                return ResourceManager.GetString("PHRASE_DO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Don&apos;t have an account.
        /// </summary>
        public static string PHRASE_DONT_HAVE_ACCOUNT {
            get {
                return ResourceManager.GetString("PHRASE_DONT_HAVE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forgot your password?.
        /// </summary>
        public static string PHRASE_FORGOT_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("PHRASE_FORGOT_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        public static string PHRASE_LOGIN {
            get {
                return ResourceManager.GetString("PHRASE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Minimun 6 characters.
        /// </summary>
        public static string PHRASE_PASSWORD_REQUIREMENTS {
            get {
                return ResourceManager.GetString("PHRASE_PASSWORD_REQUIREMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create your account!.
        /// </summary>
        public static string PHRASE_REGISTER_YOUR_ACCOUNT {
            get {
                return ResourceManager.GetString("PHRASE_REGISTER_YOUR_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Small tasks, big results.
        /// </summary>
        public static string PHRASE_SMALL_TASKS_BIG_RESULTS {
            get {
                return ResourceManager.GetString("PHRASE_SMALL_TASKS_BIG_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error ocurred while communicating with the server, Please try again later..
        /// </summary>
        public static string SERVER_COMMUNICATION_ERROR {
            get {
                return ResourceManager.GetString("SERVER_COMMUNICATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Control your routine with ease - because you deserve more time for what you love!.
        /// </summary>
        public static string SUBTITLE_REGISTER_ACCOUNT {
            get {
                return ResourceManager.GetString("SUBTITLE_REGISTER_ACCOUNT", resourceCulture);
            }
        }
    }
}
